### ISSUE TITLE
Ensure proper backend validation on every endpoint

### ISSUE THREAD

**Issue by herasymj** [No-Patience/Core#43]
- Prevent user from completely booking a doctor

**Comment by ShawnClake** [comment]
Also needs to validate whether or not a user has the right roles for accessing that endpoint. IE - A doctor account should not be able to use the verify doctor endpoint etc. etc.

**Comment by herasymj** [comment]
- Admin being the only ones who can access unverified clinics/doctors

**Comment by herasymj** [comment]
Check if fields being sent to endpoint are fully filled out

**Comment by ShawnClake** [comment]
This is too vague now especially with the amount of endpoints that exist. Closing in favor of more specific validation issues.
