### ISSUE TITLE
==True needs to be changed to ==1 for Boolean flag columns; check whether Alchemy has a boolean parameter for models

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Core#47]
Perhaps worth checking whether this was really the problem or if there's another subtle bug with how the model is setup. For example, perhaps there's a decorator or parameter you need to set on boolean columns in the model and then Alchemy will do the conversion for you.

**Comment by herasymj** [comment]
SQLAlchemy cannot handle the 'is' or 'is not' keywords, this is what is causing this issue. Will need to go through and make sure no queries use those keywords
