### ISSUE TITLE
If data is not sent to an endpoint such as PUT /users data should not be set to null/undefined/blank

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Core#56]
In various endpoints (in particular PUT /users), the implementation dictates that almost all of the fields be sent with an API request or it will set them to undefined/null/blank. Instead, checks should be done for each field before overwriting its current value.

IE:
if user.first_name:
  first_name = user.first_name

**Comment by herasymj** [comment]
Leave values blank you do not want to update
