### ISSUE TITLE
Fix error when starting appointments

### ISSUE THREAD

**Issue by TristanHeisler** [No-Patience/Core#74]
Currently, core fails when attempting to start an appointment using the endpoint below:
POST /appointments/{id}/start

Error message:
core          | sqlalchemy.exc.DataError: (_mysql_exceptions.DataError) (1265, "Data truncated for column 'status' at row 1")
core          | [SQL: UPDATE appointment SET actual_start_time=%s, status=%s WHERE appointment.id = %s]
core          | [parameters: (datetime.datetime(2019, 3, 30, 21, 26, 26, 390080), 'in_progress', 88)]
core          | (Background on this error at: http://sqlalche.me/e/9h9h)

**Comment by herasymj** [comment]
Pretty sure this is caused by the new in_progress status I added but didn't migrate
